package notes;

public class Aboutjava {
	/*
	<1>Write Java code and save the file with .java
	<2>Now, this file will be compiled using the Java compiler, which is javac.
	<3>The Java Compiler will compile the Java file and create a .class file having byte code ( which is not actually a machine code, unlike the C compiler)
	<4>This generated byte code is a non-executable code, and now it needs an interpreter to convert it into machine code. Here the JVM handles it.
	<5>Now, JVM will execute this byte code to execute Java byte code on a machine.
	<6>Now, our program will perform the functionality and gives the desired output.
	*/

}
